The changes include:
COS-IN/iluvatar-faas pull request #10
Opened 2023-11-28 20:21 UTC by abrehman94

configuration to work on Jetson

  Scaphandra Specific
    Getting the process ID (PID) of a container and its target server
    Using a single listener thread approach to find child thread PIDs

  Tegrastat invocation for energy monitoring

  GPU functions
    Avoiding the use of nvidia-smi on Tegra
    Adding Nvidia runtime flags for container invocation
    Creating a new folder for Jetson functions

2023-11-29 16:32 UTC, aFuerst requested changes
Your code is also failing clippy/format checks. Please address those issues as well.
You may need to update cargo to get latest clippy rules

2023-11-29 16:32 UTC, aFuerst commented on src/load/functions/python3/functions/1_pyaes_2000/main.py
You don't need to create custom functions for different arguments. You can pass arguments in the load generator via the metadata. See the [gpu-benchmark](https://github.com/COS-IN/iluvatar-faas/blob/master/src/Il%C3%BAvatar/il%C3%BAvatar_load_gen/src/resources/gpu-benchmark.csv).
Just add all your functions as variations with different arguments.

2023-11-29 16:32 UTC, aFuerst commented on src/Ilúvatar/ilúvatar_load_gen/src/resources/cpu-benchmark-v-21-dd.csv
These resource files are "all existing functions managed by this repo", just split into GPU/CPU/all files.
Jetson-specific ones are fine, but for experiment-specific splits, please keep them somewhere else

2023-11-29 16:32 UTC, aFuerst commented on src/Ilúvatar/docs/examples/start_worker.sh
This won't run on an arbitrary setup. An example should work anywhere.

2023-11-29 16:32 UTC, aFuerst commented on src/Ilúvatar/ilúvatar_load_gen/src/trace/trace_utils.rs
> +        }
Don't hardcode memory settings or config. These should be set in the metadata csv file on trace load

2023-11-29 16:32 UTC, aFuerst commented on src/Ilúvatar/ilúvatar_worker/src/worker_jetson.json
> +        "is_tegra": true
is this the only difference between this file and the `worker.json`? If so, just remove this and add `is_tegra` as `false` to the base file. It can be overridden at runtime

2023-11-29 16:32 UTC, aFuerst commented on src/Ilúvatar/ilúvatar_worker_library/src/services/containers/docker/docker.rs
> +            if let Some(gpu_config) = self.config.gpu_resource.clone() {
You don't need the `clone()`, `as_ref()` should work.

2023-11-29 16:32 UTC, aFuerst commented on src/Ilúvatar/ilúvatar_worker_library/src/services/invocation/queueing_dispatcher.rs
> +                if !wr.is_none(){
use `if let Some(wr)` over `is_none`/`unwrap`

2023-11-29 16:32 UTC, aFuerst commented on src/Ilúvatar/ilúvatar_worker_library/src/services/resources/gpu.rs
> +            let gpu_uuid = "291aa685-fbb1-44ec-8a5d-79550dc13f55".to_string();
is this universal for every tegra? This should be loaded dynamically

2023-11-29 16:32 UTC, aFuerst commented on src/load/functions/python3/jetson/start_image.sh
These are all errata development files. Please remove them

2023-11-29 16:32 UTC, aFuerst commented on src/load/functions/python3/using_cli/config.sh
Again, remove errata files

2023-12-04 21:12 UTC, abrehman94 commented on src/load/functions/python3/functions/1_pyaes_2000/main.py
remove

2023-12-04 21:13 UTC, abrehman94 commented on src/Ilúvatar/ilúvatar_load_gen/src/resources/cpu-benchmark-v-21-dd.csv
removed

2023-12-04 21:13 UTC, abrehman94 commented on src/Ilúvatar/docs/examples/start_worker.sh
removed

2023-12-04 21:13 UTC, abrehman94 commented on src/Ilúvatar/ilúvatar_load_gen/src/trace/trace_utils.rs
> +        }
removed

2023-12-04 21:13 UTC, abrehman94 commented on src/Ilúvatar/ilúvatar_worker/src/worker_jetson.json
> +        "is_tegra": true
removed - default is handled in the code

2023-12-04 21:13 UTC, abrehman94 commented on src/Ilúvatar/ilúvatar_worker_library/src/services/containers/docker/docker.rs
> +            if let Some(gpu_config) = self.config.gpu_resource.clone() {
changed

2023-12-04 21:13 UTC, abrehman94 commented on src/Ilúvatar/ilúvatar_worker_library/src/services/invocation/queueing_dispatcher.rs
> +                if !wr.is_none(){
changed

2023-12-04 21:14 UTC, abrehman94 commented on src/Ilúvatar/ilúvatar_worker_library/src/services/resources/gpu.rs
> +            let gpu_uuid = "291aa685-fbb1-44ec-8a5d-79550dc13f55".to_string();
there is no way to retrieve uuid for tegra

this is a randomly generated uuid to fill the place holder

2023-12-04 21:14 UTC, abrehman94 commented on src/load/functions/python3/jetson/start_image.sh
removed

2023-12-04 21:14 UTC, abrehman94 commented on src/load/functions/python3/using_cli/config.sh
removed

2023-12-06 14:36 UTC, aFuerst requested changes

2023-12-06 14:36 UTC, aFuerst commented on src/Ilúvatar/Makefile
> +	@cargo clippy --fix -- -Dclippy::suspicious -Dclippy::correctness -Dclippy::perf -Aclippy::single_match -Aclippy::new_without_default -Aclippy::too_many_arguments -Aclippy::type-complexity -Dclippy:
Don't do this. It will fix issues _inside_ the PR build, but they won't be propagated to your branch/PR.

You can make a new make target that runs this command though, but you need to run it locally and push the changes

2023-12-06 14:36 UTC, aFuerst commented on src/Ilúvatar/ilúvatar_library/src/energy/energy_layer.rs
> +impl Default for DataExtractorVisitor {
Why do you need all these extra `Default` impls?

2023-12-06 14:36 UTC, aFuerst commented on src/Ilúvatar/ilúvatar_worker_library/src/services/containers/containerd/containerd.rs
> +            bg_workqueue: thread::spawn(move || loop {
We've got helpers for this kind of thing to make code match.

https://github.com/COS-IN/iluvatar-faas/blob/master/src/Il%C3%BAvatar/iluvatar_library/src/threading.rs#L27

2023-12-06 14:36 UTC, aFuerst commented on src/Ilúvatar/ilúvatar_worker_library/src/services/invocation/queueing_dispatcher.rs
> +                if let Some(wr) = &result_ptr.worker_result.as_ref() {
This should still log that the invocation completed, even if the worker result is empty.
Add an `else` with the log log message too

2023-12-06 14:36 UTC, aFuerst commented on src/Ilúvatar/ilúvatar_worker_library/src/services/resources/gpu.rs
> +            let gpu_uuid = "291aa685-fbb1-44ec-8a5d-79550dc13f55".to_string();
How does the `--gpus` to Docker work then? Regularly it needs the GPU uuid to mount. So if this uuid is unrelated, it just always mounts the tegra accelerator?

2023-12-24 16:05 UTC, abrehman94 commented on src/Ilúvatar/Makefile
> +	@cargo clippy --fix -- -Dclippy::suspicious -Dclippy::correctness -Dclippy::perf -Aclippy::single_match -Aclippy::new_without_default -Aclippy::too_many_arguments -Aclippy::type-complexity -Dclippy:
Sorry about that, didn't see that it was being used for the PR build.

2023-12-26 14:32 UTC, aFuerst approved these changes

2023-12-26 14:32 UTC, merged